// template
export const POST_IMAGE_ACTION = "POST_IMAGE_ACTION";
export const HANDLE_SUBMISSION_ACTION = "HANDLE_SUBMISSION_ACTION";
export const HANDLE_EVENT_SUBMISSION_ACTION = "HANDLE_EVENT_SUBMISSION_ACTION";
export const GET_INVENTORY_ACTION = "GET_INVENTORY_ACTION";
export const GET_SINGLE_ITEM_ACTION = "GET_SINGLE_ITEM_ACTION";
export const UPDATE_INVENTORY_ACTION = "UPDATE_INVENTORY_ACTION";
